### ISSUE TITLE
When using the application in Top Screen Only Mode and windowed, the virtual cursor sends multiple unintended inputs.

### ISSUE THREAD

**Issue by ag-advania** [ag-advania/melonPrimeDS#48]
Same issue in Makidoll repo: 
https://github.com/makidoll/melonPrimeDS/issues/5

**Comment by Zection6V** [comment]
Is it still happening? I don't think so

**Comment by ag-advania** [comment]
Still an issue for example writing friends code is too hard

**Comment by Zection6V** [comment]
Confirmed it's solved in new version

**Comment by Zection6V** [comment]
Its still happening in windowed mode

**Comment by Zection6V** [comment]
- When using the application in Top Screen Only Mode and windowed, the virtual cursor sends multiple unintended inputs.
   - Workaround: To avoid this issue, you can assign another key to simulate a touch input instead of directly clicking. For example, setting the "V" key to act as a touch input button(Scan key) prevents the virtual cursor from sending multiple inputs.
